import { NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';
import crypto from 'crypto';
import { supabase } from '@/lib/supabase';

// ------------------------------------------------------------------
// 2. jsPDF GENERATION LOGIC
// ------------------------------------------------------------------
async function generatePDF(data) {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });
    
    // Header
    doc.setFont('times', 'bold');
    doc.setFontSize(18);
    doc.text('CIVICLENS', 20, 20);
    
    // Meta Info
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.text(`REPORT ID: ${data.reportId}`, 130, 15);
    doc.text(`GENERATED: ${new Date().toISOString().split('T')[0]}`, 130, 20);
    
    // Line separator
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);
    
    // Subject lines
    doc.setFontSize(10);
    doc.setFont('courier', 'bold');
    doc.text('SUBJECT: WARD RESOLUTION REPORT', 20, 35);
    doc.text(`SUMMARY ID: ${data.summaryId}`, 20, 40);
    
    // Issue Summary Section
    doc.setFont('times', 'bold');
    doc.setFontSize(12);
    doc.text('Issue Summary (System Generated)', 20, 55);
    doc.setLineWidth(0.2);
    doc.line(20, 57, 190, 57);
    
    doc.setFont('times', 'normal');
    doc.setFontSize(11);
    doc.text(`Ward: ${data.wardNo}`, 20, 65);
    doc.text(`Problem Type: ${data.problemType}`, 20, 72);
    doc.text(`Date Reported: ${new Date(data.dateReported).toLocaleDateString()}`, 20, 79);
    doc.text(`Source: Official CivicLens Portal`, 20, 86);
    
    doc.setFont('times', 'bold');
    doc.text('Summary Text:', 20, 96);
    
    // Handle multiline summary text
    doc.setFont('times', 'normal');
    const splitSummary = doc.splitTextToSize(data.summaryText || 'No summary text provided.', 160);
    doc.text(splitSummary, 25, 103);
    
    // Manager section starting dynamic Y pos
    const currentY = Math.max(103 + (splitSummary.length * 5) + 15, 130);
    
    doc.setFont('times', 'bold');
    doc.setFontSize(12);
    doc.text('Manager Resolution Statement', 20, currentY);
    doc.line(20, currentY + 2, 190, currentY + 2);
    
    doc.setFont('times', 'normal');
    doc.setFontSize(11);
    doc.text(`Final Status: RESOLVED`, 20, currentY + 10);
    doc.text(`Manager Name: ${data.managerName}`, 20, currentY + 17);
    doc.text(`Resolution Time: ${new Date().toISOString()}`, 20, currentY + 24);
    
    doc.setFont('times', 'bold');
    doc.text('Manager Remarks:', 20, currentY + 34);
    
    // Handle multiline remarks text
    doc.setFont('times', 'normal');
    const splitRemarks = doc.splitTextToSize(data.managerRemarks || 'No remarks provided.', 160);
    doc.text(splitRemarks, 25, currentY + 41);
    
    // Footer / declaration
    const decY = 230;
    doc.setLineWidth(0.5);
    doc.line(20, decY, 190, decY);
    doc.setFont('times', 'italic');
    doc.text(`I, Ward ${data.wardNo} Manager, hereby declare under penalty of administrative action`, 20, decY + 10);
    doc.text(`that the above issue has been successfully resolved in accordance with civic standards.`, 20, decY + 15);
    
    doc.setFont('times', 'normal');
    doc.text('Signed (Electronic)', 20, decY + 40);
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.text(`${new Date().toISOString()}`, 20, decY + 45);
    
    doc.setFont('times', 'bold');
    doc.setFontSize(11);
    doc.text(`Manager Ward No. ${data.wardNo}`, 140, decY + 40);
    doc.setFont('times', 'normal');
    doc.text(`Ward Manager, Annual Contract`, 140, decY + 45);
    
    // Footer page info
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.text(`Page 1 of 1 • Generated by CivicLens Governance Platform`, 105, 285, { align: 'center' });
    
    // Output as array buffer and convert to node Buffer
    const arrayBuffer = doc.output('arraybuffer');
    return Buffer.from(arrayBuffer);
}

// ------------------------------------------------------------------
// 3. SHA-256 HASHING LOGIC
// ------------------------------------------------------------------
function computePDFHash(pdfBuffer) {
    return crypto.createHash('sha256').update(pdfBuffer).digest('hex');
}


// ------------------------------------------------------------------
// 4. API ENDPOINT LOGIC
// ------------------------------------------------------------------
export async function POST(request) {
    try {
        const body = await request.json();
        const { complaintId } = body;

        // --- VALIDATION START ---
        if (!complaintId) {
            return NextResponse.json({ success: false, error: 'Complaint ID required' }, { status: 400 });
        }

        // Parse ID (c{ward}-{summaryId})
        const idParts = complaintId.substring(1).split('-');
        if (idParts.length !== 2) return NextResponse.json({ success: false, error: 'Invalid ID' }, { status: 400 });
        const wardNo = parseInt(idParts[0]);
        const summaryId = parseInt(idParts[1]);

        // Fetch Complaint Data
        const { data: complaint, error } = await supabase
            .from('SummaryTable')
            .select('*')
            .eq('ward_no', wardNo)
            .eq('summaryId', summaryId)
            .single();

        if (error || !complaint) {
            return NextResponse.json({ success: false, error: 'Complaint not found' }, { status: 404 });
        }

        // Rule: PDF allowed ONLY if status = RESOLVED
        if (complaint.manager_workflow_status !== 'Resolved') {
            return NextResponse.json({ success: false, error: 'Report generation only allowed for RESOLVED complaints.' }, { status: 403 });
        }

        // Rule: Manager remarks are mandatory
        if (!complaint.managerRemarks || !complaint.managerRemarks.trim()) {
            return NextResponse.json({ success: false, error: 'Manager remarks are mandatory for report generation.' }, { status: 400 });
        }
        // --- VALIDATION END ---


        // Prepare Data for Template
        const reportData = {
            reportId: crypto.randomUUID(),
            summaryId: complaint.summaryId,
            wardNo: complaint.ward_no,
            problemType: complaint.problem_type || 'General',
            dateReported: complaint.created_at,
            summaryText: complaint.summary,
            managerName: `Ward ${complaint.ward_no} Manager`, // In real app, fetch from auth/users table
            managerRemarks: complaint.managerRemarks
        };

        // GENERATE PDF
        const pdfBuffer = await generatePDF(reportData);

        // COMPUTE HASH
        const pdfHash = computePDFHash(pdfBuffer);
        console.log('[Debug] Generated PDF Hash:', pdfHash);

        // UPLOAD TO STORAGE (Bucket: manager_pdfs)
        const fileName = `${wardNo}_${summaryId}_${reportData.reportId}.pdf`;
        const { error: uploadError } = await supabase.storage
            .from('manager_pdfs')
            .upload(fileName, pdfBuffer, {
                contentType: 'application/pdf',
                upsert: true
            });

        if (uploadError) {
            console.error('[Debug] Storage Upload Failed:', uploadError);
            return NextResponse.json({ success: false, error: 'Failed to upload report to storage. ' + uploadError.message }, { status: 500 });
        }

        // GET PUBLIC URL
        const { data: { publicUrl } } = supabase.storage
            .from('manager_pdfs')
            .getPublicUrl(fileName);

        // Update DB
        const { data: updatedData, error: updateError } = await supabase
            .from('SummaryTable')
            .update({
                pdfPath: publicUrl,
                pdfHash: pdfHash
            })
            .eq('ward_no', wardNo)
            .eq('summaryId', summaryId)
            .select();

        if (updateError) {
            console.error('Failed to update metadata:', updateError);
            return NextResponse.json({
                success: false,
                error: `Failed to record report generation. DB Error: ${updateError.message || updateError.details || 'Unknown DB error'}`
            }, { status: 500 });
        }

        return NextResponse.json({
            success: true,
            message: 'Report generated successfully',
            reportId: reportData.reportId,
            pdfHash: pdfHash
        });

    } catch (err) {
        console.error('[PDF Generation Error]:', err);
        return NextResponse.json({ success: false, error: 'Internal Server Error' }, { status: 500 });
    }
}
